# GitHub Actions CI Pipeline 
name: Integration

# On pull request or push to main branch
on:
  pull_request:
   branches:
      - main
   
# Permissions for private repo
permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  Testing:
# Set-up Linux VM 
    runs-on: 'ubuntu-latest'

# Check out repo
    steps:
    - name: checkout repo content
      uses: actions/checkout@v3

# Install Python & upgrade pip
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' 

    - name: install dependencies
      run: python -m sync

# Install dependencies & test libraries        
    - name: install testing libraries
      run: pip install pytest mock codecov pydocstyle pytest-cov pylint pylint_junit

# Run integration tests
    - name: Run codebase functional testing
      run: pytest -v tests/ --doctest-modules --junitxml=unit-testresults.xml --cov=src/ --cov-append --cov-report=xml:xmlcov --cov-report=html:htmlcov 

# Publish test results
    - name: Publish test reuslts
      uses: EnricoMi/publish-unit-test-result-action@v1.37